language: node_js
sudo: false
node_js: 10
script:
    - "yarn deps"
    - "yarn test"
branches:
    only:
    - master
after_success:
    - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
